version: 2.1
jobs:

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - chmod +x commit_check.sh
      - ./commit_check.sh
      - checkout
      # If changing build tools be sure to update GeneratorSetup.md in docs
      - run: gradle fatJar :output:test :profile:test :generator:test :common:test :orchestrator:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  release:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2e:7e:4f:29:21:87:2b:71:46:42:45:c4:9a:f4:a3:b6"
      - checkout
      - run: gradle fatJar
      # If changing build tools be sure to update GeneratorSetup.md in docs
      - run: gradle release -Dorg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Dorg.ajoberstar.grgit.auth.password
      # If not, let's try :orchestrator:release

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
# TODO: Ensure gradle migration is smooth before introducing release job
  release:
    jobs:
      - release:
          filters:
            branches:
              only: master
