version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run: mvn clean test
      - store_test_results:
          path: schemas/target/surefire-reports
      - store_test_results:
          path: generator/target/surefire-reports
workflows:
  version: 2.1
  build_and_test: 
    jobs:
      - build
