version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:

  check_commit_message:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/datahelix/
    steps:
      - checkout
      - run:
          name: Set commit script priviledges
          command: chmod +x commit_check.sh
      - run:
          name: Check commit messages
          command: ./commit_check.sh

  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      # If changing build tools be sure to update BuildAndRun.md in docs
      - run: gradle fatJar :output:test :profile:test :generator:test :common:test :orchestrator:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
      - codecov/upload:
          file: schemas/target/jacoco-reports/jacoco.xml
      - codecov/upload:
          file: generator/target/jacoco-reports/jacoco.xml

  # Release generates version x.y.z for:
  # x - BREAKING CHANGE included in commit message body
  # y - feat
  # z - fix, perf
  # Otherwise no release is created.
  # See https://github.com/tschulte/gradle-semantic-release-plugin/blob/master/src/main/groovy/de/gliderpilot/gradle/semanticrelease/SemanticReleaseChangeLogService.groovy
  release:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3f:0d:d9:6c:36:06:da:f4:1b:77:22:b9:b7:b5:ab:93"
      - checkout
      - run: gradle fatJar
      - run: gradle release -Dorg.ajoberstar.grgit.auth.username=${GH_TOKEN} -Dorg.ajoberstar.grgit.auth.password


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
# # Ignored to disable semantic versioning for now:
#      - check_commit_message:
#          filters:
#            branches:
#              ignore: master
#  release:
#    jobs:
#      - release:
#          filters:
#            branches:
#              only: master
